version: 2
updates:
  - package-ecosystem: docker
    directory: /runtime
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/London
    allow:
      - dependency-name: node
    ignore:
      - dependency-name: node
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/London
    open-pull-requests-limit: 5
