#!/usr/bin/env python3
"""Install a committed SDLC snapshot through a private local Homebrew tap."""
import argparse
import fcntl
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import stat
import subprocess
import sys
import tempfile

FORMULA = 'local/sdlc/sdlc'
TAP = 'local/sdlc'
ROOT = Path(__file__).resolve().parents[1]


class InstallError(ValueError):
    pass


def command(args, *, cwd=None, capture=False, env=None):
    result = subprocess.run(args, cwd=cwd, env=env, check=True,
                            stdout=subprocess.PIPE if capture else None,
                            text=capture)
    return result.stdout.strip() if capture else None


def regular_json(path, private=False):
    info = path.lstat()
    if (not stat.S_ISREG(info.st_mode) or info.st_size > 16384
            or (private and info.st_mode & 0o077)):
        raise InstallError(f'{path.name} must be a {"private " if private else ""}regular file under 16 KiB.')
    return json.loads(path.read_text(encoding='utf-8'))


def private_json(path):
    return regular_json(path, private=True)


def write_atomic(path, data, mode=0o600):
    if path.is_symlink():
        raise InstallError(f'Refusing to replace a symlink: {path.name}')
    with tempfile.NamedTemporaryFile(dir=path.parent, prefix='.' + path.name, delete=False) as output:
        temporary = Path(output.name)
        try:
            os.fchmod(output.fileno(), mode)
            output.write(data)
            output.flush()
            os.fsync(output.fileno())
        except BaseException:
            temporary.unlink(missing_ok=True)
            raise
    try:
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def snapshot_identity(source):
    source = source.resolve(strict=True)
    root = Path(command(['git', '-C', str(source), 'rev-parse', '--show-toplevel'], capture=True)).resolve()
    if root != source:
        raise InstallError('--source must name the SDLC checkout root.')
    if command(['git', '-C', str(source), 'status', '--porcelain', '--untracked-files=normal'], capture=True):
        raise InstallError('Homebrew packages committed source. Commit or set aside source changes before installing.')
    module = command(['git', '-C', str(source), 'show', 'HEAD:go.mod'], capture=True)
    if not re.search(r'^module\s+"?github\.com/tjpeel/sdlc"?\s*$', module, re.M):
        raise InstallError('Source must declare module github.com/tjpeel/sdlc.')
    contents = command(['git', '-C', str(source), 'show', 'HEAD:internal/buildinfo/version.go'], capture=True)
    match = re.search(r'^var Version = "(\d+\.\d+\.\d+(?:-beta\.\d+)?)"$', contents, re.M)
    if not match:
        raise InstallError('Source has no supported SDLC version declaration.')
    revision = command(['git', '-C', str(source), 'rev-parse', 'HEAD'], capture=True)
    entries = subprocess.run(['git', '-C', str(source), 'ls-tree', '-rz', '--full-tree', revision],
                             check=True, stdout=subprocess.PIPE).stdout.split(b'\0')
    if any(entry and entry.split(b' ', 1)[0] not in {b'100644', b'100755'} for entry in entries):
        raise InstallError('Homebrew snapshots require regular tracked files; review symlinks or submodules first.')
    count = int(command(['git', '-C', str(source), 'rev-list', '--count', 'HEAD'], capture=True))
    return source, match[1], revision, count


def formula_text(archive, checksum, version, revision, count):
    # JSON string quoting is also valid Ruby string quoting for paths and URLs.
    return f'''# Generated by SDLC; refresh with sdlc update or install_homebrew.py.
# SDLC snapshot: {revision}
require "digest"
require "json"

class Sdlc < Formula
  desc "Local software delivery workflow with official coding clients"
  homepage "https://github.com/tjpeel/sdlc"
  url {json.dumps(archive.as_uri(), ensure_ascii=False)}
  version "{version}"
  sha256 "{checksum}"
  revision {count}
  depends_on "go" => :build

  def install
    system "go", "build", "-trimpath", "-buildvcs=false",
           "-ldflags=-X github.com/tjpeel/sdlc/internal/buildinfo.Revision={revision}",
           "-o", bin/"sdlc", "./cmd/sdlc"
    (libexec/"source").install Dir["*", ".[^.]*"]
    manifest = {{schema_version: 1, formula: "{FORMULA}", version: "{version}",
                revision: "{revision}", sha256: Digest::SHA256.file(bin/"sdlc").hexdigest}}
    (libexec/"sdlc-homebrew.json").write JSON.generate(manifest)
  end

  def caveats
    "Run sdlc runtime build --source-pins to prepare Docker. Account state stays outside the Cellar."
  end

  test do
    assert_match "sdlc {version}", shell_output("#{{bin}}/sdlc --version")
    assert_match "verified Homebrew package", shell_output("#{{bin}}/sdlc version --details --json")
  end
end
'''


def digest(path):
    result = hashlib.sha256()
    with path.open('rb') as source:
        for block in iter(lambda: source.read(1024 * 1024), b''):
            result.update(block)
    return result.hexdigest()


def real_directory(path):
    if path.is_symlink():
        raise InstallError(f'Directory must not be a symlink: {path.name}')
    path.mkdir(mode=0o700, exist_ok=True)
    if not path.is_dir():
        raise InstallError(f'Expected a directory: {path.name}')


def migration_backup(destination, state):
    """Permit only the previous receipt-verified native install or our tap."""
    if not destination.exists() and not destination.is_symlink():
        return None
    if destination.is_symlink():
        package_identity(destination)
        return None
    if not destination.is_file():
        raise InstallError('Existing sdlc is not a regular managed executable.')
    receipt = private_json(state / 'installation.json')
    if (receipt.get('schema_version') != 1
            or Path(receipt.get('executable', '')).resolve() != destination.resolve()
            or receipt.get('sha256') != digest(destination)):
        raise InstallError('Existing sdlc does not match its installation receipt; it was left in place.')
    return digest(destination)


def package_identity(candidate):
    executable = candidate.resolve(strict=True)
    keg = executable.parent.parent
    if executable.name != 'sdlc' or executable.parent.name != 'bin' or keg.parent.name != 'sdlc':
        raise InstallError('Candidate is outside an SDLC Homebrew keg.')
    manifest = regular_json(keg / 'libexec/sdlc-homebrew.json')
    # Homebrew receipts include inventories larger than our small manifest.
    receipt_path = keg / 'INSTALL_RECEIPT.json'
    info = receipt_path.lstat()
    if not stat.S_ISREG(info.st_mode) or info.st_size > 1024 * 1024:
        raise InstallError('Homebrew receipt must be a regular file under 1 MiB.')
    receipt = json.loads(receipt_path.read_text(encoding='utf-8'))
    if (manifest.get('schema_version') != 1 or manifest.get('formula') != FORMULA
            or receipt.get('source', {}).get('tap') != TAP
            or manifest.get('sha256') != digest(executable)):
        raise InstallError('Candidate checksum or receipt does not belong to this Homebrew tap.')
    return manifest


def prepare_package(source, state, brew, env, version, revision, count):
    package_dir = state / 'homebrew'
    real_directory(package_dir)
    archives = package_dir / 'archives'
    real_directory(archives)
    archive = archives / f'sdlc-{revision}.tar.gz'
    with tempfile.NamedTemporaryFile(dir=archives, prefix='.archive-', delete=False) as output:
        temporary = Path(output.name)
        try:
            subprocess.run(['git', '-C', str(source), 'archive', '--format=tar.gz',
                            '--prefix=sdlc/', revision], stdout=output, check=True)
            output.flush()
            os.fsync(output.fileno())
            os.replace(temporary, archive)
        finally:
            temporary.unlink(missing_ok=True)
    repository = Path(command([brew, '--repository'], capture=True, env=env))
    tap = repository / 'Library/Taps/local/homebrew-sdlc'
    marker = tap / 'sdlc-local-tap.json'
    if tap.is_symlink():
        raise InstallError('Local tap must be a real directory.')
    if tap.exists():
        if private_json(marker) != {'schema_version': 1, 'state_directory': str(state)}:
            raise InstallError('local/sdlc already exists and belongs to another installation.')
    else:
        command([brew, 'tap-new', '--no-git', TAP], env=env)
        write_atomic(marker, json.dumps({'schema_version': 1, 'state_directory': str(state)}).encode())
    formula = tap / 'Formula/sdlc.rb'
    if formula.exists():
        info = formula.lstat()
        if not stat.S_ISREG(info.st_mode) or info.st_size > 65536:
            raise InstallError('Local formula must be a regular file under 64 KiB.')
        previous = formula.read_text(encoding='utf-8')
        old_revision = re.search(r'^# SDLC snapshot: ([a-f0-9]{40})$', previous, re.M)
        old_count = re.search(r'^  revision (\d+)$', previous, re.M)
        if not old_revision or not old_count:
            raise InstallError('Local formula metadata is invalid; it was left in place.')
        # Amending or signing changes a commit ID without changing its count.
        # Preserve a counter for the same snapshot; advance it for new content.
        count = max(count, int(old_count[1]) + (old_revision[1] != revision))
    text = formula_text(archive, digest(archive), version, revision, count)
    real_directory(tap / 'Formula')
    write_atomic(tap / 'Formula/sdlc.rb', text.encode('utf-8'), 0o644)
    write_atomic(state / 'homebrew.json', json.dumps({
        'schema_version': 1, 'formula': FORMULA, 'source': str(source),
    }).encode())


def install(args):
    source, version, revision, count = snapshot_identity(args.source)
    brew = shutil.which('brew')
    if brew is None:
        raise InstallError('Homebrew is required; install it before running this command.')
    state = args.state_dir.expanduser().absolute()
    print(f'Homebrew: {FORMULA}\nSource: {source}\nSnapshot: {version} ({revision})', flush=True)
    if args.dry_run:
        print('Would refresh the local formula/checksum and install or upgrade the committed snapshot.')
        print('Runtime: unchanged (--cli-only)' if args.cli_only else
              'Runtime: refresh dependencies' if args.dependencies else 'Runtime: rebuild with source pins')
        return
    command([sys.executable, str(source / 'scripts/check_sensitive.py'), '--worktree'], cwd=source)
    # Keep generated paths, source archives and coordination state private.
    if state.is_symlink():
        raise InstallError('State directory must be a real directory.')
    state.mkdir(mode=0o700, parents=True, exist_ok=True)
    state = state.resolve(strict=True)
    env = dict(os.environ, HOMEBREW_NO_AUTO_UPDATE='1', HOMEBREW_NO_INSTALL_CLEANUP='1',
               HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK='1', HOMEBREW_NO_ASK='1', SDLC_STATE_DIR=str(state))
    if not env.get('SDLC_UPDATE_PROJECT_ROOT'):
        caller = subprocess.run(['git', 'rev-parse', '--show-toplevel'],
                                stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True)
        if caller.returncode == 0:
            env['SDLC_UPDATE_PROJECT_ROOT'] = str(Path(caller.stdout.strip()).resolve(strict=True))
    prefix = Path(command([brew, '--prefix'], capture=True, env=env)).resolve(strict=True)
    destination = prefix / 'bin/sdlc'
    found = shutil.which('sdlc')
    if found and Path(found).absolute() != destination:
        raise InstallError('Another sdlc resolves first on PATH; select Homebrew bin before installing.')
    lock_path = state / 'homebrew-install.lock'
    descriptor = os.open(lock_path, os.O_CREAT | os.O_RDWR | os.O_NOFOLLOW, 0o600)
    with os.fdopen(descriptor, 'w') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        previous_hash = migration_backup(destination, state)
        prepare_package(source, state, brew, env, version, revision, count)
        installed = subprocess.run([brew, 'list', '--versions', FORMULA], env=env,
                                   stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True)
        if installed.returncode == 0 and installed.stdout.strip():
            if previous_hash:
                # A previous link failure can leave our validated new keg beside
                # the restored native CLI. Reuse it without touching that CLI.
                candidate = Path(command([brew, '--prefix', FORMULA], capture=True, env=env)) / 'bin/sdlc'
                package_identity(candidate)
                actual = command([str(candidate), '--version'], capture=True, env=env)
                if f'sdlc {version} ({revision};' not in actual:
                    raise InstallError('An unlinked Homebrew keg has a different snapshot. Run '
                                       f'brew uninstall {FORMULA}, then retry; the native CLI is still in place.')
            else:
                command([brew, 'upgrade', FORMULA], env=env)
        else:
            command([brew, 'install', '--skip-link', FORMULA], env=env)
        candidate = Path(command([brew, '--prefix', FORMULA], capture=True, env=env)) / 'bin/sdlc'
        manifest = package_identity(candidate)
        if manifest.get('version') != version or manifest.get('revision') != revision:
            raise InstallError('Homebrew package metadata describes a different snapshot; update was stopped.')
        actual = command([str(candidate), '--version'], capture=True, env=env)
        if f'sdlc {version} ({revision};' not in actual:
            raise InstallError('Homebrew selected a different snapshot; CLI/runtime update was stopped.')
        if previous_hash:
            if migration_backup(destination, state) != previous_hash:
                raise InstallError('Existing CLI changed during the build; it was left in place.')
            backup_dir = state / 'homebrew/backups'
            real_directory(backup_dir)
            backup = backup_dir / f'sdlc-{previous_hash}'
            shutil.copy2(destination, backup)
            destination.unlink()
            try:
                command([brew, 'link', FORMULA], env=env)
            except BaseException:
                if destination.is_symlink() and destination.resolve() == candidate.resolve():
                    destination.unlink()
                if not destination.exists() and not destination.is_symlink():
                    shutil.copy2(backup, destination)
                raise
            print(f'Previous CLI backed up: {backup}', flush=True)
        elif not destination.exists():
            command([brew, 'link', FORMULA], env=env)
        print(f'Installed {actual} through Homebrew.', flush=True)
        if not args.cli_only:
            runtime_source = candidate.resolve().parent.parent / 'libexec/source'
            runtime_args = [str(candidate), 'runtime', 'build', '--source', str(runtime_source), '--source-pins']
            if args.dependencies:
                if not (state / 'runtime.json').exists():
                    command(runtime_args, env=env)
                runtime_args = [str(candidate), 'runtime', 'update', '--source', str(runtime_source)]
            try:
                command(runtime_args, env=env)
            except subprocess.CalledProcessError as error:
                raise InstallError('Homebrew installed the CLI, but runtime preparation failed. '
                                   'The runtime command above reports its result; retry sdlc update after resolving it.') from error


def main(argv=None):
    default_state = Path(os.environ.get('SDLC_STATE_DIR', '')) if os.environ.get('SDLC_STATE_DIR') else (
        Path.home() / 'Library/Application Support/sdlc' if sys.platform == 'darwin' else
        Path(os.environ.get('XDG_CONFIG_HOME', str(Path.home() / '.config'))) / 'sdlc')
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=ROOT)
    parser.add_argument('--state-dir', type=Path, default=default_state)
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument('--cli-only', action='store_true', help='Keep the existing runtime unchanged.')
    modes.add_argument('--dependencies', action='store_true', help='Refresh public runtime dependencies.')
    parser.add_argument('--dry-run', action='store_true', help='Preview without builds, writes or network access.')
    args = parser.parse_args(argv)
    try:
        install(args)
    except (InstallError, OSError, ValueError, subprocess.SubprocessError) as error:
        print(f'Homebrew installation failed: {error}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
